# ------------------------------------------
# Configuration
# ------------------------------------------

title: ZooPhotonics
author: ZooPhotonics
description: A research team developing wildlife monitoring systems

url: https://zoophotonics.com
icon: /static/images/icon.png
mask: /static/images/mask.svg
banner: /static/images/banner.png
color: 555ABF

sass:
  sass_style: compressed

exclude:
- .gitignore
- Gemfile
- Gemfile.lock
- Rakefile
- README.md